timing:
  max_steps: 400000

data:
  name: spoc-style
  task: err-compiler
  splits:
    train:
      format: substitute
      paths: [../data/err-data-compiler--auto-corrupt--codeforce--spoc-style/*/*.json]
      shuffle: true
    dev:
      format: vanilla
      path: ../data/err-dev-compiler--for-pretrain-spoc/err-dev.1000.jsonl
    test:
      format: vanilla
      path: ../data/err-dev-compiler--for-pretrain-spoc/err-dev.1000.jsonl
  vocab:
    path: ../data/err-vocab-compiler--for-spoc/combined.vocab
    min_freq: 2
